apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-microservice
  template:
    metadata:
      labels:
        app: k8s-microservice
    spec:
      containers:
      - name: k8s-microservice
        image: k8s-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
